/**
 * plbx_html playable adapter
 * Generated by Playbox extension.
 *
 * One adapter wires every ad network the extension supports — MRAID
 * (AppLovin/Unity/IronSource), Facebook/Moloco (FbPlayableAd), Mintegral
 * (window.install), Google (ExitApi), TikTok/Pangle (playableSDK), and
 * Moloco V2.0 (Launcher API) with MOLOCO_MACROS beacons.
 *
 * Usage:
 *   import plbx from './plbx_html/plbx_html_playable';
 *   plbx.download();       // redirect to store
 *   plbx.game_end();       // notify ad network that gameplay ended
 *   plbx.is_audio();       // check if audio is allowed
 *   plbx.expose(name, fn); // register a command external callers can trigger
 *
 * --- Wire these calls into your Cocos game lifecycle ---
 *
 *   1. onLoad / scene init:        plbx.game_ready();
 *   2. every user tap:             plbx.tap();
 *   3. CTA button onClick:         plbx.download();
 *   4. level finished:             plbx.game_end();
 *   5. before audio init:          if (plbx.is_muted()) ctx.suspend();
 *
 * Without these calls, network validators (Moloco V2, Mintegral PlayTurbo,
 * etc.) will not detect lifecycle beacons and may flag the creative.
 *
 * --- Optional: external commands (preview "Game commands" toolbar) ---
 *
 * Register handlers external callers (ad container, test harness, or the
 * Playbox panel preview) can invoke. The preview renders one button per
 * registered command, so you can drive these states without playing through:
 *
 *   onLoad() {
 *       plbx.expose('show_endcard', () => this.showEndcard(), 'Show endcard');
 *       plbx.expose('restart',      () => this.restart(),      'Restart');
 *   }
 *
 * Register AFTER the scene can handle the action. External callers then trigger
 * it via window.plbx_html.show_endcard(). The optional 3rd arg is the preview
 * button label (defaults to the command name).
 */
export class plbx_html_playable {

    /**
     * Call when the user taps the CTA / DOWNLOAD button.
     * Fires the network click beacon and opens the store URL.
     */
    download() {
        console.log("[plbx] download");
        //@ts-ignore
        if (window.plbx_html) { plbx_html.download(); }
        //@ts-ignore
        else if (window.super_html) { super_html.download(); }
    }

    /**
     * Call ONCE when the scene is loaded and the game is ready to display.
     * Fires the game_viewable beacon (Moloco V2) and gameReady signal
     * (Mintegral / TikTok / Pangle validators).
     */
    game_ready() {
        console.log("[plbx] game_ready");
        //@ts-ignore
        if (window.plbx_html && plbx_html.game_ready) { plbx_html.game_ready(); }
        //@ts-ignore
        else if (window.super_html && super_html.game_ready) { super_html.game_ready(); }
    }

    /**
     * Call when the playable level / gameplay session finishes (success or fail).
     * Fires the complete beacon and gameEnd signal.
     */
    game_end() {
        console.log("[plbx] game_end");
        //@ts-ignore
        if (window.plbx_html) { plbx_html.game_end(); }
        //@ts-ignore
        else if (window.super_html) { super_html.game_end(); }
    }

    /**
     * Call on every meaningful user tap / interaction.
     * Used by Moloco V2 to count taps against taps_for_engagement /
     * taps_for_redirection thresholds. Safe no-op on non-Moloco networks.
     */
    tap() {
        //@ts-ignore
        if (window.plbx_html && plbx_html.tap) { plbx_html.tap(); }
        //@ts-ignore
        else if (window.super_html && super_html.tap) { super_html.tap(); }
    }

    /**
     * Fire a custom MOLOCO_MACROS beacon by key. Use for ad-hoc tracking
     * outside the standard lifecycle (e.g. "tutorial_completed").
     * No-op on non-Moloco networks.
     */
    report(eventKey: string) {
        //@ts-ignore
        if (window.plbx_html && plbx_html.report) { plbx_html.report(eventKey); }
        //@ts-ignore
        else if (window.super_html && super_html.report) { super_html.report(eventKey); }
    }

    is_audio(): boolean {
        //@ts-ignore
        if (window.plbx_html && plbx_html.is_audio) {
            //@ts-ignore
            return plbx_html.is_audio();
        }
        //@ts-ignore
        if (window.super_html && super_html.is_audio) {
            //@ts-ignore
            return super_html.is_audio();
        }
        return true;
    }

    /**
     * Returns the current muted state of the ad container. Seeded from the
     * start-time signal (Moloco V2 MOLOCO_MACROS.start_muted, etc.) and kept
     * live via MRAID audioVolumeChange. Call before initializing AudioContext
     * or unmuting any media element. For continuous reaction use on_mute_change.
     */
    is_muted(): boolean {
        //@ts-ignore
        if (window.plbx_html && plbx_html.is_muted) {
            //@ts-ignore
            return plbx_html.is_muted();
        }
        //@ts-ignore
        if (window.super_html && super_html.is_muted) {
            //@ts-ignore
            return super_html.is_muted();
        }
        return false;
    }

    /**
     * Subscribe to live mute changes. The callback fires immediately with the
     * current state, then again whenever the ad container's volume crosses
     * mute/unmute (MRAID audioVolumeChange). Use this to start/stop music in
     * response to the user toggling sound on the ad wrapper mid-playback.
     * No-op on networks without a live volume signal (callback still gets the
     * initial state once).
     */
    on_mute_change(cb: (muted: boolean) => void): void {
        //@ts-ignore
        if (window.plbx_html && plbx_html.on_mute_change) {
            //@ts-ignore
            plbx_html.on_mute_change(cb);
            return;
        }
        //@ts-ignore
        if (window.super_html && super_html.on_mute_change) {
            //@ts-ignore
            super_html.on_mute_change(cb);
            return;
        }
        // Fallback: deliver the one-shot current state so callers can rely on
        // at least one invocation.
        try { cb(this.is_muted()); } catch (e) { /* ignore */ }
    }

    is_hide_download(): boolean {
        //@ts-ignore
        if (window.plbx_html && plbx_html.is_hide_download) {
            //@ts-ignore
            return plbx_html.is_hide_download();
        }
        return false;
    }

    set_google_play_url(url: string) {
        //@ts-ignore
        if (window.plbx_html) { plbx_html.google_play_url = url; }
        //@ts-ignore
        if (window.super_html) { super_html.google_play_url = url; }
    }

    set_app_store_url(url: string) {
        //@ts-ignore
        if (window.plbx_html) { plbx_html.appstore_url = url; }
        //@ts-ignore
        if (window.super_html) { super_html.appstore_url = url; }
    }

    /**
     * Register a named command that external callers can invoke — the ad
     * container, a test harness, or the Playbox panel preview (which renders a
     * trigger button per command in its "Game commands" toolbar).
     *
     *   plbx.expose('show_endcard', () => this.showEndcard(), 'Show endcard');
     *
     * The game implements 'fn'; external callers trigger it via
     * window.plbx_html.<name>(). 'label' is the preview button text (defaults to
     * name). Register after your scene is ready to handle the action.
     */
    expose(name: string, fn: () => void, label?: string) {
        //@ts-ignore
        if (window.plbx_html && plbx_html.expose) { plbx_html.expose(name, fn, label); }
        //@ts-ignore
        else if (window.super_html && super_html.expose) { super_html.expose(name, fn, label); }
        else { console.log("[plbx] expose unavailable (update the Playbox extension): " + name); }
    }
}
export default new plbx_html_playable();
